# Generated by Django 4.2.4 on 2024-05-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('dni', models.CharField(max_length=8, verbose_name='Dni')),
                ('apellido_nombre', models.CharField(max_length=250, verbose_name='Apellidos y Nombres')),
                ('grado', models.CharField(max_length=12, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=1, verbose_name='Sección')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asist', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha_registro', models.DateField(verbose_name='Fecha')),
                ('hora_registro', models.TimeField(verbose_name='Hora')),
                ('alumno', models.CharField(max_length=250, verbose_name='Apellidos y Nombres')),
                ('dni_almn', models.CharField(max_length=8, verbose_name='Dni')),
                ('grado', models.CharField(max_length=12, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=1, verbose_name='Sección')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_eta',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('dni_alumno', models.CharField(max_length=8, verbose_name='Dni')),
                ('nombre_eta', models.CharField(max_length=50, verbose_name='Nombre ETA')),
                ('matematica', models.FloatField(max_length=2, verbose_name='Nota Matemática')),
                ('raz_matematico', models.FloatField(max_length=2, verbose_name='Nota Razonamiento Matemático')),
                ('comunicacion', models.FloatField(max_length=2, verbose_name='Nota Comunicación')),
                ('raz_verbal', models.FloatField(max_length=2, verbose_name='Nota Razonamiento Verbal')),
                ('ciencias_sociales', models.FloatField(max_length=2, verbose_name='Nota Ciencias Sociales')),
                ('cta', models.FloatField(max_length=2, verbose_name='Nota CTA')),
                ('ingles', models.FloatField(max_length=2, verbose_name='Nota Inglés')),
                ('dpcc', models.FloatField(max_length=2, verbose_name='Nota DPCC')),
            ],
        ),
    ]
