# Generated by Django 4.2.4 on 2024-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_eta',
            name='ciencias_sociales',
            field=models.FloatField(max_length=2, verbose_name='Nota CCSS'),
        ),
        migrations.AlterField(
            model_name='resultado_eta',
            name='comunicacion',
            field=models.FloatField(max_length=2, verbose_name='Nota Comu'),
        ),
        migrations.AlterField(
            model_name='resultado_eta',
            name='matematica',
            field=models.FloatField(max_length=2, verbose_name='Nota Mat'),
        ),
        migrations.AlterField(
            model_name='resultado_eta',
            name='raz_matematico',
            field=models.FloatField(max_length=2, verbose_name='Nota Raz Matemático'),
        ),
        migrations.AlterField(
            model_name='resultado_eta',
            name='raz_verbal',
            field=models.FloatField(max_length=2, verbose_name='Nota Raz Verbal'),
        ),
    ]
