# Generated by Django 4.2.4 on 2024-06-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0002_alter_resultado_eta_ciencias_sociales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_asist',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultado_eta',
            name='id_result',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
