# Generated by Django 4.2.4 on 2024-06-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0003_alter_alumno_id_alumno_alter_asistencia_id_asist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='id_alumno',
            new_name='id',
        ),
    ]
