# Generated by Django 4.2.4 on 2024-06-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0004_rename_id_alumno_alumno_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_asist',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='resultado_eta',
            old_name='id_result',
            new_name='id',
        ),
    ]
