# Generated by Django 4.2.4 on 2024-06-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0005_rename_id_asist_asistencia_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado_eta',
        ),
    ]
